name: Build (.dmg)
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: 
permissions:
   contents: write
   actions: read
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install create-dmg
      run: brew install create-dmg
    
    - name: Build Xcode project (unsigned)
      run: |
        xcodebuild -project RSSReader.xcodeproj \
          -scheme "RSSReader" \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Verify and prepare app
      run: |
        ls -la "build/Build/Products/Release/"
        # Remove quarantine attributes
        sudo xattr -cr "build/Build/Products/Release/RSSReader.app"
        # Make executable
        chmod +x "build/Build/Products/Release/RSSReader.app/Contents/MacOS/"*
    
    - name: Create DMG
      run: |
        create-dmg \
          --volname "RSS Reader" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --app-drop-link 600 185 \
          --hdiutil-quiet \
          "RSSReader.dmg" \
          "build/Build/Products/Release/RSSReader.app"
        
        # Remove quarantine from DMG
        sudo xattr -cr "RSSReader.dmg"
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: RSSReader.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation Instructions
          
          Since this app isn't App Store signed, you may need to:
          1. Right-click the app and select "Open" 
          2. Or run: `sudo xattr -rd com.apple.quarantine /Applications/RSSReader.app`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rss-reader-dmg
        path: "RSSReader.dmg"
