# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build (.dmg)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install create-dmg
      run: brew install create-dmg
    
    - name: Build Xcode project
      run: |
        xcodebuild -project RSSReader.xcodeproj -scheme RSS-Reader -configuration Release -derivedDataPath build
    
    - name: Verify app was built
      run: |
        ls -la "build/Build/Products/Release/"
        file "build/Build/Products/Release/RSS-Reader.app"
    
    - name: Create DMG
      run: |
        create-dmg \
          --volname "RSS Reader" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --app-drop-link 600 185 \
          "RSSReader.dmg" \
          "build/Build/Products/Release/RSS-Reader.app"
    
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rss-reader-dmg
        path: "RSSReader.dmg"
